### ISSUE TITLE
Feature Proposal : Display a warning if the gem has a know vulnerability

### ISSUE THREAD

**Issue by Yoshyn** [buttercloud/atom-gem-wiseguy#4]
Hi,

It will be cool to have something like : https://github.com/rubysec/bundler-audit.
(As it will make another web request, it's not something that will be activated by default)

It seem [that bundler-audit](https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/database.rb) is based on [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db)

Here the list of the know vulnerability : https://github.com/rubysec/ruby-advisory-db/tree/master/gems

What you think about this idea?

**Comment by afhammad** [comment]
The wiser gem-wiseguy can be, the better! Feel free to submit a PR.

**Comment by Yoshyn** [comment]
I will take a look when,when i got time. :)

**Comment by Yoshyn** [comment]
[Closing some of my old pending issues]
